spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect # Specify the MySQL dialect here
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/school123123?serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: school
server:
  port: 5051

eureka:
  instance:
    hostname: localhost # Hostname of the Eureka server
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
